apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    tier: backend
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 80
  selector:
    app: nginx
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  # modify it according to your case
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        tier: backend
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
