apiVersion: v1
kind: Service
metadata:
  name: payara
  labels:
    app: payara
    tier: backend
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 8080
    name: "http"
  - port: 4848
    name: "admin"
  selector:
    app: payara
    tier: backend
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: payara
  labels:
      cloudcontrol.enabled: "true"
      cloudcontrol.index: "0"
      LAUNCHPAD_ENABLE: "true"
      LAUNCHPAD_COLOR: ORANGE
      LAUNCHPAD_ROW: "0"
spec:
  # modify it according to your case
  replicas: 2
  template:
    metadata:
      labels:
        app: payara
        tier: backend
    spec:
      containers:
      - name: payara
        image: payara/server-full:173
        ports:
        - containerPort: 8080
        - containerPort: 4848
